### ISSUE TITLE
Android mobiles >> Submit feedback >> Legal links >> underline issue >>  

### ISSUE THREAD

**Issue by SycamoreFoxQA** [FoxDigitalMarketing/avatar-php#49] opened 2018-03-30 10:02 UTC
When we hit on any of the legal links and return to the same page, underline below the legal link disappears.

By default, the underline is present for both the links.

Please refer the screenshot.

Devices: Mobiles
Browser: Chrome 65, 
OS: Android 7.0, 8.0

![underline](https://user-images.githubusercontent.com/17753858/38134143-72671906-342f-11e8-8c63-4eef0b44194a.jpg)

**Comment by omniwired** [comment] 2018-04-02 08:11
I tried to repro in a Google Pixel 2 XL, using the same browser version. But couldn't.
I don't think this is a high priority either.

**Comment by damyantid** [comment] 2018-04-02 17:25
Closing this issue as I cannot reproduce on my Samsung S8 Note.

**Closed by damyantid** 2018-04-02 17:25 UTC
Labels: Can't Reproduce

**Comment by SycamoreFoxQA** [comment] 2018-04-03 10:04
OK.
